context:
  name: sleap-io
  version: 0.1.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/sleap_io-${{ version }}.tar.gz
  sha256: 5a067f0fd7590f67effef4c559a352ae15ffc34b7005970c01f726b9e8b0365c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - ffmpeg
    - imageio
    - imageio-ffmpeg >=0.5.0
    - attrs
    - pandas
    - simplejson
    - h5py >=3.8.0
    - hdmf
    - numpy
    - opencv
    - pynwb
    - ndx-pose <0.2.0

tests:
  - python:
      imports:
        - sleap_io
  - requirements:
      run:
        - pip
        - if: linux
          then: libopencv *=headless*
    script:
      - pip check

about:
  summary: Standalone utilities for working with pose data from SLEAP and other tools.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/talmolab/sleap-io
  documentation: https://io.sleap.ai

extra:
  recipe-maintainers:
    - talmo
